
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AYMANE
 */
public class Gestion_des_notes extends javax.swing.JFrame {

    /**
     * Creer dans papani
     */
    Connecter conn = new Connecter();
    Statement stm;
    ResultSet Rs;
    DefaultTableModel model = new DefaultTableModel();
    
    public Gestion_des_notes() {
        initComponents();
        
        model.addColumn("id");
        model.addColumn("nom");
        model.addColumn("prenom");
        model.addColumn("branche");
        model.addColumn("note");
        
        try {
            stm=conn.obtenirconnexion().createStatement();
            ResultSet Rs = stm.executeQuery("Select * from etudiant");
            while(Rs.next()){
                model.addRow(new Object[] {Rs.getString("id"), Rs.getString("Nom"), Rs.getString("Prenom"), 
                    Rs.getString("Branche"), Rs.getString("note")});
            }
        } catch (Exception e) {
            System.err.println(e);
        }
        tble.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtno = new javax.swing.JTextField();
        txtpr = new javax.swing.JTextField();
        txtnot = new javax.swing.JTextField();
        txtbr = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tble = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(3850, 3002));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ajouter.png"))); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 340, 140, 40);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/actualiser.png"))); // NOI18N
        jButton2.setText("Actualiser");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 340, 140, 40);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/supprimer.png"))); // NOI18N
        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(230, 420, 140, 40);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/modifier.png"))); // NOI18N
        jButton4.setText("Modifier");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(60, 420, 140, 40);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rechercher.png"))); // NOI18N
        jButton5.setText("Recherche");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(410, 380, 160, 40);

        txtre.setBackground(new java.awt.Color(255, 204, 204));
        txtre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreActionPerformed(evt);
            }
        });
        getContentPane().add(txtre);
        txtre.setBounds(590, 380, 140, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("           PAPANI");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 20, 370, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("id :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 90, 49, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Nom :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 140, 49, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Prenom:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 190, 60, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Branche :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 250, 60, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("Note :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 300, 60, 17);

        txtid.setBackground(new java.awt.Color(153, 153, 153));
        txtid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid);
        txtid.setBounds(160, 90, 70, 30);

        txtno.setBackground(new java.awt.Color(153, 153, 153));
        txtno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoActionPerformed(evt);
            }
        });
        getContentPane().add(txtno);
        txtno.setBounds(160, 140, 70, 30);

        txtpr.setBackground(new java.awt.Color(153, 153, 153));
        txtpr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtpr);
        txtpr.setBounds(160, 200, 70, 30);

        txtnot.setBackground(new java.awt.Color(153, 153, 153));
        txtnot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnotActionPerformed(evt);
            }
        });
        getContentPane().add(txtnot);
        txtnot.setBounds(160, 300, 70, 23);

        txtbr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INFO", "ALGO", "CULTURE GENERALE", "FRANCAIS", "ANGLAIS", "ECO DROIT", "HISTOIRE GEO", "EPS", "PHYSIQUE", "CHIMIE", "ALGEBRE", "GEOMETRIE", "MATHS", "SVT", "SPECIALITE" }));
        txtbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbrActionPerformed(evt);
            }
        });
        getContentPane().add(txtbr);
        txtbr.setBounds(160, 250, 70, 20);

        tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Titre 5"
            }
        ));
        tble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tble);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(280, 90, 410, 230);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bio.jpg"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(1200, 800));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 10, 1350, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void deplace(int i){

    try {
        txtid.setText(model.getValueAt(i,0).toString());
        txtno.setText(model.getValueAt(i,1).toString());
        txtpr.setText(model.getValueAt(i,2).toString());
        txtbr.setSelectedItem(model.getValueAt(i,3).toString());
        txtnot.setText(model.getValueAt(i,4).toString());
        
    } catch (Exception e) {
        System.err.println(e);
        JOptionPane.showMessageDialog(null, "erreur de deplacement" + e.getLocalizedMessage());
    }
}
private void afficher(){
    try {
            model.setRowCount(0);
            stm=conn.obtenirconnexion().createStatement();
            ResultSet Rs = stm.executeQuery("Select * from etudiant");
            while(Rs.next()){
                model.addRow(new Object[] {Rs.getString("id"), Rs.getString("Nom"), Rs.getString("Prenom"), 
                    Rs.getString("Branche"), Rs.getString("note")});
            }
        } catch (Exception e) {
            System.err.println(e);
        }
        tble.setModel(model);
}
    private void txtnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoActionPerformed

    private void txtnotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnotActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id=txtid.getText();
        String nom=txtno.getText();
        String prenom=txtpr.getText();
        String branche=txtbr.getSelectedItem().toString();
        String note=txtnot.getText();
        String requete="insert into etudiant(id,Nom, Prenom, branche, note )VALUES ('"+id+"','"+nom+"','"+prenom+"','"+branche+"','"+note+"')";        
        
        try {
            stm.executeUpdate(requete);
            JOptionPane.showMessageDialog(null, "l'etudiant(e) est bien ajouté(e)");
            txtno.setText("");
            txtpr.setText("");
            txtbr.setSelectedItem(2);
            txtnot.setText("");
            afficher();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  afficher();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            if(JOptionPane.showConfirmDialog(null, "êtes-vous sûr de vouloir supprimer ?",
                    "supprimer etudiant", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
                
                if(txtid.getText().length() != 0){
                    stm.executeUpdate("Delete from etudiant where id = "+txtid.getText());
                    afficher();
                }else{
                    JOptionPane.showMessageDialog(null, "veuillez remplir le champ id !");
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erreur de suppression \n"+e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreActionPerformed

    private void tbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbleMouseClicked
        try {
            int i=tble.getSelectedRow();deplace(i);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"erreur de deplacement"+ e.getLocalizedMessage());
        }
    }//GEN-LAST:event_tbleMouseClicked

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            if(JOptionPane.showConfirmDialog(null, "confirmer la modification","modification",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                
                stm.executeUpdate("Update etudiant SET Nom='"+txtno.getText()+"',Prenom='"+txtpr.getText()+
                        "',branche = '"+txtbr.getSelectedItem().toString()+"',note= "+txtnot.getText()+
                        " WHERE id= "+txtid.getText() );
              
                afficher();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erreur de modification ! "+ e.getMessage());
                    System.err.println(e);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            model.setRowCount(0);
            {
                Rs = stm.executeQuery("Select * From etudiant WHERE Nom= '"+txtre.getText()+"'");
                }
            while(Rs.next()){
                Object[] etudient = {Rs.getInt(1), Rs.getString(2), Rs.getString(3), Rs.getString(4),Rs.getInt(5)};
                 model.addRow(etudient);
            }
               
            if(model.getRowCount () == 0){JOptionPane.showMessageDialog(null, "il n'y a aucun(e) etudiant(e) à ce nom veuillez saisir un nom existant");
            }else{int i=0;
                  deplace(i);}
        } catch (Exception e) {
    System.err.println(e);
    JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbrActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_des_notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_des_notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_des_notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_des_notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_des_notes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tble;
    private javax.swing.JComboBox<String> txtbr;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtno;
    private javax.swing.JTextField txtnot;
    private javax.swing.JTextField txtpr;
    private javax.swing.JTextField txtre;
    // End of variables declaration//GEN-END:variables
}
